### PR TITLE
Allow highcharts to be used in 'style mode'

### PR DESCRIPTION
**Pull request by butzopower**
Highcharts 5 added the ability to style charts via CSS rather than sending style options through to the chart.  See: http://www.highcharts.com/docs/chart-design-and-style/style-by-css 

This change allows the choice between `styledMode` and `classicMode` when importing `ChartModule`.  If only the `ChartModule` is provided, then `classicMode` will be used by default.

Here is how a basic Angular application would use either:

### Classic mode

```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    CommonModule,
    FormsModule,
    ChartModule.classicMode
  ],
  providers: [],
  entryComponents: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

or just like before with plain ol' `ChartModule`:

```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    CommonModule,
    FormsModule,
    ChartModule
  ],
  providers: [],
  entryComponents: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

### Styled mode

```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    CommonModule,
    FormsModule,
    ChartModule.styledMode
  ],
  providers: [],
  entryComponents: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

### CODE REVIEW

**Comment by butzopower** [comment]
#115

**Comment by gevgeny** [comment]
thanks for the pr. i will review and merge later

**Comment by gevgeny** [comment]
@butzopower I think "style mode" can be achieved just by small updades in the build config. Look at this https://github.com/gevgeny/angular2-webpack-starter-and-angular2-highcharts/commit/c585a6b076b9b52b7e647fae58d7147bb2f910dd

**Comment by mannb1** [comment]
Just commenting in hopes of getting a heads up when this is merged, would like to play with the style mode

**Comment by iacii** [comment]
I would also like this feature. I used a CLI created by my company (layered over the Angular CLI) to initialize my Angular app and cannot modify the webpack config. Having the ability to import `ChartModule.styledMode` would be very helpful.

**Pull request closed without merging**
