### PR TITLE
Compile code using ngc

### LINKED ISSUE #75: Error: Unexpected value 'ChartModule' imported by the module 'AppModule'
I am using `angular2-highcharts` with Ionic 2 RC.0. But I am getting the following error:

```
[12:52:35]  ngc error: Error: Unexpected value 'ChartModule' imported by the module 'AppModule'
    at node_modules/@angular/compiler/bundles/compiler.umd.js:14113:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (node_modules/@angular/compiler/bundles/compiler.umd.js:14096:46)
    at node_modules/@angular/compiler/bundles/compiler.umd.js:12937:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (node_modules/@angular/compiler/bundles/compiler.umd.js:12936:21)
    at CodeGenerator.codegen (node_modules/@angular/compiler-cli/src/codegen.js:105:47)
```

I am using it like this:

```
// app.module.js
import { ChartModule } from 'angular2-highcharts';

@NgModule({
  imports: [
    ...
    ChartModule, 
    ...
  ],
  ...
})
export class AppModule { }
```

Error happens when I do `npm run build`. Any ideas?

### PR DESCRIPTION
**Pull request by fank**
Fixes #75 

@gevgeny just check package.json

### CODE REVIEW

**Comment by gevgeny** [comment]
the travis build is red :(

**Comment by fank** [comment]
ill take a look again :D

**Comment by fank** [comment]
Now this should be more then green, BTW we should only enable the squash merge option. Its the best way to keep the commit history readable.

**Review by michael-brade — APPROVED** [review]

**Comment by gevgeny** [comment]
np

**Pull request merged**
