### PR TITLE
Updated to angular2@2.0.0

### PR DESCRIPTION
**Pull request by fank**
We need a working version for RC5 for our application, so i updated it.
The only problem test aren't working as expected, test files are updated as well, but don't know how to fix.

### CODE REVIEW

**Comment by fank** [comment]
Ah and FYI the import has changed:

``` ts
import {ChartModule} from 'angular2-highcharts';

@NgModule({
    imports: [
        ChartModule,
    ],
})
export class AppModule {}
```

**Comment by gevgeny** [comment]
Sorry, I cannot merge PR with broken tests

**Comment by maxailloud** [comment]
@Fank can you consider updating your PR as this will really help transitionning to Angular2 final version (and help for #64 of course)?
Or maybe @gevgeny just help him finishing it?

It's really something needed for people to use it as for now it's not compatible anymore with Angular2.

**Comment by fank** [comment]
@maxailloud sure i also can update to stable, i may only need help with the tests

**Comment by maxailloud** [comment]
@Fank Nice, it will be really nice of you.
Yeah I didn't know if this was something you can do that's why I asked @gevgeny if he can gives you a hand.

**Comment by fank** [comment]
@maxailloud i squashed all commits, test works also as expected. If CI is green you are ready to merge.

**Comment by maxailloud** [comment]
@Fank Yeah nice work man.

@gevgeny I think we are ready to go here.

**Review by jdelaune — APPROVED** [review]

**Review by maxailloud — APPROVED** [review]

**Comment by elvisbegovic** [comment]
I do not understand what is in this  issue, it is supported by ng2 final release or not ? how can I achieve this because I have this error actually 

> "Unexpected directive 'ChartComponent' imported by the module 'AppModule'"

UPDATE add this to declaration instead import

**Comment by fank** [comment]
@istiti It support it, we are using the version in the PR and it works fine.

**Comment by istiti** [comment]
@Fank  thanks for fast reply but I'm using the Basic usage and I have error, how achieve ? here is my gif http://g.recordit.co/QMju91CZRR.gif

**Comment by dantullis** [comment]
@Frank How can I use it? How do I do a "npm install" against a PR?

**Comment by fank** [comment]
@istiti @dantullis here an how to use example:
1. install the npm version: `npm install mcl-de/angular2-highcharts`
2. import the module into your NgModule:

``` ts
import {ChartModule} from 'angular2-highcharts';

@NgModule({
    imports: [
        ChartModule,
    ],
})
export class AppModule {}
```
1. now you can use the components, you dont need to import anything else JUST use them.

**Comment by dantullis** [comment]
@Frank  Thanks! Let me know if it should be done differently, but I actually did need to the following import:

`import { Highcharts } from 'angular2-highcharts/dist/';`

so I could use setOptions for the basic chart example.

`Highcharts.setOptions({
    colors: ['#058DC7', '#50B432', '#ED561B']
});`

**Comment by maxailloud** [comment]
@gevgeny We need you here.

**Comment by Kianian** [comment]
@Fank I did it same, but it has error:
```

XXXXX:38 Error: Error: Unexpected value 'undefined' imported by the module 'XXXXXModule'(…)

(anonymous function) @ XXXXX:38ZoneDelegate.invoke 
@ zone.js:192Zone.run 
@ zone.js:85(anonymous function) 
@ zone.js:451ZoneDelegate.invokeTask 
@ zone.js:225Zone.runTask 
@ zone.js:125drainMicroTaskQueue 
@ zone.js:357ZoneTask.invoke 
@ zone.js:297
```

**Comment by BenoitFroment** [comment]
@Fank 
i can't run ur npm install, could u please make a zip of the package? 
until PR updated

thanks

**Comment by honify** [comment]
Guys, I have fixed it without upgrade, I have installed the package from main repository.

`npm install angular2-highcharts --save
`

Then I have changed something in the Modules:

`import { CHART_DIRECTIVES } from 'angular2-highcharts';
`

```
@NgModule({
    declarations: [CHART_DIRECTIVES],
    exports: [CHART_DIRECTIVES],
    ....
```

Then I have removed all the declarations from anywhere else.
It works perfect.

**Comment by gevgeny** [comment]
Thanks guys! Great work. And sorry for the delay. Now I am updating readme and then publish new version.
PS @Fank Welcome to direct collaborators ;)

**Comment by fank** [comment]
@gevgeny thx

**Comment by maxailloud** [comment]
@gevgeny Can you release the new version on npm?
It hasn't been done, or bug don't know.

**Comment by gevgeny** [comment]
I would like to update the live demos before publishing to npm. will do these days.

**Comment by maxailloud** [comment]
Sure no problem.

**Comment by renehamburger** [comment]
@gevgeny, I've been trying to install the current master branch via npm, but the postinstall `typings install` failed if typings isn't already installed, which surprised me. We've moved to using the npm `@types` modules instead as does angular-cli.
Once that was fixed, I got lots of TypeScript 'duplicate identifier' issues caused by the global es6-shim and jasmine typings installed by angular2-highcharts.

Can you remove the postinstall script altogether and add it to the README.md for people who want to run your tests?

**Comment by Sfairet** [comment]
@renehamburger, i have same problem on @Fank version. 
+1

**Comment by fank** [comment]
@Sfairet can you show us the error message/log?

**Comment by Sfairet** [comment]
@Fank, I can not now repeat the exact error, but the meaning was "typings not installed".
On production i havnt typings in dependencies, but when i try `npm install mcl-de/angular2-highcharts`, starts postinstall script `typings install`, which caused this error.

I installed temporarily typings on production and all work fine.

**Comment by renehamburger** [comment]
typings is one of the 'devDependencies' in package.json, as it should be, so it's not installed when angular2-highcharts is installed as a dependency. Best to remove the postinstall script.

**Comment by aderbas** [comment]
I'm using Angular 2.1.0 with angular-cli, when I run: `ng build`:

```
 94% asset optimizationError in bail mode: [default] /var/www/html/test-app/node_modules/angular2-highcharts/dist/ChartComponent.d.ts:12:25 
Cannot find name 'HighchartsChartObject'.
```

I'm just create a new clean project and install `npm install angular2-highcharts --save` and put in `app.module.ts`:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { ChartModule } from 'angular2-highcharts';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    ChartModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

I need anything else?

**Pull request merged**
